platform :ios, '7.0'

pod 'Mapbox', :git => 'https://github.com/mapbox/mapbox-ios-sdk', :branch => 'release'
pod 'AFNetworking'
pod 'gtm-oauth'
pod 'MBProgressHUD'
pod 'CocoaLumberjack'
pod 'TBXML'
pod 'FMDB'
pod 'BButton'
pod 'DAKeyboardControl'
pod 'TTTAttributedLabel'
pod 'ActionSheetPicker'
pod 'SDWebImage'