platform :ios, '7.0'

pod 'Mapbox-iOS-SDK'
pod 'AFNetworking'
pod 'gtm-oauth'
pod 'MBProgressHUD'
pod 'CocoaLumberjack'
pod 'TBXML'
pod 'FMDB'
pod 'BButton'
pod 'DAKeyboardControl'
pod 'TTTAttributedLabel'
pod 'ActionSheetPicker'
pod 'SDWebImage'